# Generated by Django 4.2.4 on 2023-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_criminals_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminals',
            name='date_created',
            field=models.CharField(auto_created=True, default='07/09/2023 17:59', max_length=20),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
    ]
